# -*- coding: utf-8 -*-
"""
Created on Wed Jun  9 14:41:03 2021

@author: amarczak
"""
# Just the summary of the Project is shown if you don't call a point.

import requests
url = 'https://svannet.com/api/v2/projects-get-data.php'
myobj = {'key': '979e338c4416e0067bcb3e22125f75638b5dad53a36efd1a3562ce5d84794d9b'}

getProject_API = requests.post(url, data = myobj)
print(getProject_API.json())
print( )


ProjectList = getProject_API.json()

# A detailed list of the files can be generated by specifing the project ID and the Measurement Point (station)

url = 'https://svannet.com/api/v2/projects-get-data.php'
myobj = {'key': '979e338c4416e0067bcb3e22125f75638b5dad53a36efd1a3562ce5d84794d9b', 'project': 3639, 'point' : 0}

getFilelist_API = requests.post(url, data = myobj)
print(getFilelist_API.json())
print( )

ProjectContent = getFilelist_API.json()

#Or finally - downloading data as .CSV (Doesn't work for .WAV files)

url = 'https://svannet.com/api/v2/projects-get-data.php'
myobj = {'key': '979e338c4416e0067bcb3e22125f75638b5dad53a36efd1a3562ce5d84794d9b', 'project': 3639, 'point' : 0, 
         'station_type' : 307, 'station_serial' : 94194, 'day_code' : 20210513, 'filename' : '20210513_08_48_22_149452.SVL', 'action' : 1}

getFile_API = requests.post(url, data = myobj)
print(getFile_API.text)

# The .SVL file is converted to an CSV string - You can further use the script to export it as a .CSV file if you wish too. 


