<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Rvt.Storage.Abstractions/Rvt.Storage.Abstractions.csproj" />
    <ProjectReference Include="../../src/Rvt.Storage.AzureBlob/Rvt.Storage.AzureBlob.csproj" />
    <ProjectReference Include="../../src/Rvt.Storage.Local/Rvt.Storage.Local.csproj" />
    <ProjectReference Include="../../src/Rvt.Storage.S3/Rvt.Storage.S3.csproj" />
  </ItemGroup>
</Project>
