// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RVT.DataAccess.Context;

#nullable disable

namespace RVT.DataAccess.Migrations
{
    [DbContext(typeof(RVTDbContext))]
    [Migration("20260714132042_CanonicalBaseline")]
    partial class CanonicalBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RVT.Entities.Alertlevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alert_field");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<int>("AveragingPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("averaging_period");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double>("LimitOff")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_off");

                    b.Property<double>("LimitOn")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_on");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<bool>("Saturdays")
                        .HasColumnType("boolean")
                        .HasColumnName("saturdays");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<bool>("Sundays")
                        .HasColumnType("boolean")
                        .HasColumnName("sundays");

                    b.Property<bool>("Weekdays")
                        .HasColumnType("boolean")
                        .HasColumnName("weekdays");

                    b.HasKey("Id")
                        .HasName("pk_rvt_alert_rule");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_rvt_alert_rule_monitor_id");

                    b.ToTable("rvt_alert_rule", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<DateTime?>("OffHireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("off_hire_date");

                    b.Property<DateTime>("OnHireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("on_hire_date");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_contract");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_contract_company_id");

                    b.HasIndex("SiteiD")
                        .HasDatabaseName("ix_contract_site_id");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<string>("PictureLink")
                        .HasColumnType("text")
                        .HasColumnName("picture_link");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("What3words")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("what_3_words");

                    b.HasKey("Id")
                        .HasName("pk_deployment");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_deployment_contract_id");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_deployment_monitor_id");

                    b.ToTable("deployment", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.HelpArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_section_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_help_article");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_help_article_help_section_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_help_article_slug");

                    b.ToTable("help_article", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.HelpAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("HelpArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_article_id");

                    b.Property<string>("InternalPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("internal_path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_help_asset");

                    b.HasIndex("HelpArticleId")
                        .HasDatabaseName("ix_help_asset_help_article_id");

                    b.ToTable("help_asset", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.HelpSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_help_section");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_help_section_slug");

                    b.ToTable("help_section", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Monitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("archive_reason");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("archived_by");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_date");

                    b.Property<DateTime?>("CalibrationDue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_due");

                    b.Property<string>("CustomerDisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_display_name");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("firmware_version");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<DateTime?>("LastDataTime15Min")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time_15_min");

                    b.Property<DateTime?>("LastDataTime1Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time_1_hour");

                    b.Property<DateTime?>("LastDataTime1Min")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time_1_min");

                    b.Property<DateTime?>("LastDataTime24Hour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time_24_hour");

                    b.Property<double?>("Latitude")
                        .HasMaxLength(128)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<DateTime>("ListedAtTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listed_at_time");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location_address");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("time_zone");

                    b.Property<int>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.HasKey("Id")
                        .HasName("pk_monitor");

                    b.ToTable("monitor", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alert_field");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<int>("AveragingPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("averaging_period");

                    b.Property<Guid?>("ClosedByUser")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user");

                    b.Property<string>("ClosedNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("closed_note");

                    b.Property<DateTime?>("ClosedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_time");

                    b.Property<double>("Level")
                        .HasColumnType("double precision")
                        .HasColumnName("level");

                    b.Property<double>("LimitOn")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_on");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_time");

                    b.Property<string>("RecordingLink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recording_link");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("MonitorId")
                        .HasDatabaseName("ix_notification_monitor_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Email")
                        .HasColumnType("boolean")
                        .HasColumnName("email");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("SMS")
                        .HasColumnType("boolean")
                        .HasColumnName("sms");

                    b.Property<Guid>("SiteUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_user_id");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_notification_setting");

                    b.ToTable("notification_setting", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_2");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<string>("County")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postcode");

                    b.Property<TimeSpan?>("SatEndTime")
                        .HasColumnType("interval")
                        .HasColumnName("sat_end_time");

                    b.Property<TimeSpan?>("SatStartTime")
                        .HasColumnType("interval")
                        .HasColumnName("sat_start_time");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<TimeSpan?>("SunEndTime")
                        .HasColumnType("interval")
                        .HasColumnName("sun_end_time");

                    b.Property<TimeSpan?>("SunStartTime")
                        .HasColumnType("interval")
                        .HasColumnName("sun_start_time");

                    b.HasKey("Id")
                        .HasName("pk_site");

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.SiteArchived", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PictureLink")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("picture_link");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_site_archived");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_archived_site_id");

                    b.ToTable("site_archived", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.SiteOperatingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_site_operating_hour");

                    b.HasIndex("SiteId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_site_operating_hour_site_id_day_of_week");

                    b.ToTable("site_operating_hour", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.SiteUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("SiteContact")
                        .HasColumnType("boolean")
                        .HasColumnName("site_contact");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_site_user");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_user_site_id");

                    b.ToTable("site_user", (string)null);
                });

            modelBuilder.Entity("RVT.Entities.Alertlevel", b =>
                {
                    b.HasOne("RVT.Entities.Monitor", "Monitor")
                        .WithMany("Alertlevels")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rvt_alert_rule_monitor_id");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("RVT.Entities.Contract", b =>
                {
                    b.HasOne("RVT.Entities.Company", "Company")
                        .WithMany("Contracts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_company_id");

                    b.HasOne("RVT.Entities.Site", "Site")
                        .WithMany("Contracts")
                        .HasForeignKey("SiteiD")
                        .HasConstraintName("fk_contract_site_id");

                    b.Navigation("Company");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("RVT.Entities.Deployment", b =>
                {
                    b.HasOne("RVT.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_contract_id");

                    b.HasOne("RVT.Entities.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_monitor_id");

                    b.Navigation("Contract");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("RVT.Entities.HelpArticle", b =>
                {
                    b.HasOne("RVT.Entities.HelpSection", "Section")
                        .WithMany("Articles")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_help_article_help_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("RVT.Entities.HelpAsset", b =>
                {
                    b.HasOne("RVT.Entities.HelpArticle", "HelpArticle")
                        .WithMany("Assets")
                        .HasForeignKey("HelpArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_help_asset_help_article_id");

                    b.Navigation("HelpArticle");
                });

            modelBuilder.Entity("RVT.Entities.Notification", b =>
                {
                    b.HasOne("RVT.Entities.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_monitor_id");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("RVT.Entities.SiteArchived", b =>
                {
                    b.HasOne("RVT.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_archived_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("RVT.Entities.SiteOperatingHours", b =>
                {
                    b.HasOne("RVT.Entities.Site", "Site")
                        .WithMany("OperatingHours")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_operating_hour_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("RVT.Entities.SiteUsers", b =>
                {
                    b.HasOne("RVT.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_user_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("RVT.Entities.Company", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("RVT.Entities.HelpArticle", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("RVT.Entities.HelpSection", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("RVT.Entities.Monitor", b =>
                {
                    b.Navigation("Alertlevels");
                });

            modelBuilder.Entity("RVT.Entities.Site", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("OperatingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
