// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RVT.DataAccess.Context;

#nullable disable

namespace RVT.DataAccess.Migrations.Search
{
    [DbContext(typeof(RVTSearchContext))]
    partial class RVTSearchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.AdminDashboardDatum", b =>
                {
                    b.Property<string>("MonitorState")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("monitor_state");

                    b.Property<int?>("Nr")
                        .HasColumnType("integer")
                        .HasColumnName("nr");

                    b.ToTable((string)null);

                    b.ToView("admin_dashboard_data", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.CompanySearch", b =>
                {
                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("Contracts")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contracts");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("NrUsers")
                        .HasColumnType("integer")
                        .HasColumnName("user_count");

                    b.Property<string>("Sites")
                        .HasColumnType("text")
                        .HasColumnName("sites");

                    b.ToTable((string)null);

                    b.ToView("company_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ContractSearch", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("OffHireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("off_hire_date");

                    b.Property<DateTime>("OnHireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("on_hire_date");

                    b.Property<string>("SiteAddress")
                        .HasColumnType("text")
                        .HasColumnName("site_address");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.ToTable((string)null);

                    b.ToView("contract_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.CustomerDashboardMonitorDatum", b =>
                {
                    b.Property<string>("MonitorState")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("monitor_state");

                    b.Property<int?>("Nr")
                        .HasColumnType("integer")
                        .HasColumnName("nr");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("customer_dashboard_monitor_data", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.CustomerDashboardNotificationDatum", b =>
                {
                    b.Property<string>("AlertState")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("alert_state");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<int?>("Nr")
                        .HasColumnType("integer")
                        .HasColumnName("nr");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("customer_dashboard_notification_data", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MonitorCurrentSearch", b =>
                {
                    b.Property<bool?>("Alerts")
                        .HasColumnType("boolean")
                        .HasColumnName("alerts");

                    b.Property<bool?>("Battery")
                        .HasColumnType("boolean")
                        .HasColumnName("battery");

                    b.Property<bool?>("Cautions")
                        .HasColumnType("boolean")
                        .HasColumnName("cautions");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastDataTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool?>("OffLine")
                        .HasColumnType("boolean")
                        .HasColumnName("off_line");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.Property<string>("What3words")
                        .HasColumnType("text")
                        .HasColumnName("what_3_words");

                    b.ToTable((string)null);

                    b.ToView("monitor_current_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MonitorMeasurementRemovalImpact", b =>
                {
                    b.Property<long>("MeasurementRowCount")
                        .HasColumnType("bigint")
                        .HasColumnName("measurement_row_count");

                    b.Property<long>("MeasurementTableCount")
                        .HasColumnType("bigint")
                        .HasColumnName("measurement_table_count");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("monitor_measurement_removal_impact", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MonitorSearch", b =>
                {
                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Alerts")
                        .HasColumnType("boolean")
                        .HasColumnName("alerts");

                    b.Property<bool?>("Battery")
                        .HasColumnType("boolean")
                        .HasColumnName("battery");

                    b.Property<bool?>("Cautions")
                        .HasColumnType("boolean")
                        .HasColumnName("cautions");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastDataTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MonitorName")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("monitor_name");

                    b.Property<bool?>("OffLine")
                        .HasColumnType("boolean")
                        .HasColumnName("off_line");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.Property<string>("What3words")
                        .HasColumnType("text")
                        .HasColumnName("what_3_words");

                    b.ToTable((string)null);

                    b.ToView("monitor_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MonitorUserSearch", b =>
                {
                    b.Property<bool?>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool?>("Alerts")
                        .HasColumnType("boolean")
                        .HasColumnName("alerts");

                    b.Property<bool?>("Battery")
                        .HasColumnType("boolean")
                        .HasColumnName("battery");

                    b.Property<bool?>("Cautions")
                        .HasColumnType("boolean")
                        .HasColumnName("cautions");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<Guid?>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastDataTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool?>("OffLine")
                        .HasColumnType("boolean")
                        .HasColumnName("off_line");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("What3words")
                        .HasColumnType("text")
                        .HasColumnName("what_3_words");

                    b.ToTable((string)null);

                    b.ToView("monitor_user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MyAtmDustLevel", b =>
                {
                    b.Property<int?>("Avrg")
                        .HasColumnType("integer")
                        .HasColumnName("avrg");

                    b.Property<double?>("Pm1")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_1");

                    b.Property<double?>("Pm10")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_10");

                    b.Property<double?>("Pm25")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_2_5");

                    b.Property<double?>("PmTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_total");

                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("WeatherP")
                        .HasColumnType("double precision")
                        .HasColumnName("weather_p");

                    b.Property<double?>("WeatherRh")
                        .HasColumnType("double precision")
                        .HasColumnName("weather_rh");

                    b.Property<double?>("WeatherT")
                        .HasColumnType("double precision")
                        .HasColumnName("weather_t");

                    b.ToTable("my_atm_dust_level", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.MyAtmDustLevel8hourAvg", b =>
                {
                    b.Property<double?>("Pm1")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_1");

                    b.Property<double?>("Pm10")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_10");

                    b.Property<double?>("Pm25")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_2_5");

                    b.Property<double?>("PmTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("pm_total");

                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("my_atm_dust_level_8_hour_avg", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NoiseLevel15minAvg", b =>
                {
                    b.Property<double?>("La10")
                        .HasColumnType("double precision")
                        .HasColumnName("la_10");

                    b.Property<double?>("La90")
                        .HasColumnType("double precision")
                        .HasColumnName("la_90");

                    b.Property<double?>("Laeq")
                        .HasColumnType("double precision")
                        .HasColumnName("laeq");

                    b.Property<double?>("Lamax")
                        .HasColumnType("double precision")
                        .HasColumnName("lamax");

                    b.Property<double?>("Lc10")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_10");

                    b.Property<double?>("Lc90")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_90");

                    b.Property<double?>("Lceq")
                        .HasColumnType("double precision")
                        .HasColumnName("lceq");

                    b.Property<double?>("Lcmax")
                        .HasColumnType("double precision")
                        .HasColumnName("lcmax");

                    b.Property<DateTime?>("SampleTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("noise_level_15_min_avg", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NoiseLevel1dayAvg", b =>
                {
                    b.Property<double?>("La10")
                        .HasColumnType("double precision")
                        .HasColumnName("la_10");

                    b.Property<double?>("La90")
                        .HasColumnType("double precision")
                        .HasColumnName("la_90");

                    b.Property<double?>("Laeq")
                        .HasColumnType("double precision")
                        .HasColumnName("laeq");

                    b.Property<double?>("Lamax")
                        .HasColumnType("double precision")
                        .HasColumnName("lamax");

                    b.Property<double?>("Lc10")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_10");

                    b.Property<double?>("Lc90")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_90");

                    b.Property<double?>("Lceq")
                        .HasColumnType("double precision")
                        .HasColumnName("lceq");

                    b.Property<double?>("Lcmax")
                        .HasColumnType("double precision")
                        .HasColumnName("lcmax");

                    b.Property<DateTime?>("SampleTime")
                        .HasColumnType("date")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("noise_level_1_day_avg", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NoiseLevel1hourAvg", b =>
                {
                    b.Property<double?>("La10")
                        .HasColumnType("double precision")
                        .HasColumnName("la_10");

                    b.Property<double?>("La90")
                        .HasColumnType("double precision")
                        .HasColumnName("la_90");

                    b.Property<double?>("Laeq")
                        .HasColumnType("double precision")
                        .HasColumnName("laeq");

                    b.Property<double?>("Lamax")
                        .HasColumnType("double precision")
                        .HasColumnName("lamax");

                    b.Property<double?>("Lc10")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_10");

                    b.Property<double?>("Lc90")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_90");

                    b.Property<double?>("Lceq")
                        .HasColumnType("double precision")
                        .HasColumnName("lceq");

                    b.Property<double?>("Lcmax")
                        .HasColumnType("double precision")
                        .HasColumnName("lcmax");

                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("noise_level_1_hour_avg", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NoiseLevelSiteAvg", b =>
                {
                    b.Property<double?>("La10")
                        .HasColumnType("double precision")
                        .HasColumnName("la_10");

                    b.Property<double?>("La90")
                        .HasColumnType("double precision")
                        .HasColumnName("la_90");

                    b.Property<double?>("Laeq")
                        .HasColumnType("double precision")
                        .HasColumnName("laeq");

                    b.Property<double?>("Lamax")
                        .HasColumnType("double precision")
                        .HasColumnName("lamax");

                    b.Property<double?>("Lc10")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_10");

                    b.Property<double?>("Lc90")
                        .HasColumnType("double precision")
                        .HasColumnName("lc_90");

                    b.Property<double?>("Lceq")
                        .HasColumnType("double precision")
                        .HasColumnName("lceq");

                    b.Property<double?>("Lcmax")
                        .HasColumnType("double precision")
                        .HasColumnName("lcmax");

                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.ToTable((string)null);

                    b.ToView("noise_level_site_avg", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NotificationSearch", b =>
                {
                    b.Property<string>("AlertField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alert_field");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_date");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastDataTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time");

                    b.Property<double>("Level")
                        .HasColumnType("double precision")
                        .HasColumnName("level");

                    b.Property<double>("LimitOn")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_on");

                    b.Property<Guid?>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_time");

                    b.Property<string>("SerialId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int?>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.ToTable((string)null);

                    b.ToView("notification_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.NotificationUserSearch", b =>
                {
                    b.Property<string>("AlertField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("alert_field");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_date");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contract_number");

                    b.Property<string>("FleetNr")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fleet_nr");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastDataTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_time");

                    b.Property<double>("Level")
                        .HasColumnType("double precision")
                        .HasColumnName("level");

                    b.Property<double>("LimitOn")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_on");

                    b.Property<Guid?>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTime>("NotificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_time");

                    b.Property<string>("SerialId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid?>("SiteiD")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int?>("TypeOfMonitor")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_monitor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("notification_user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsMonitorStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AlarmValue")
                        .HasColumnType("double precision")
                        .HasColumnName("alarm_value");

                    b.Property<bool>("AtopEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("atop_enabled");

                    b.Property<string>("BuildingLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("building_level");

                    b.Property<double?>("DataSaveLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("data_save_level");

                    b.Property<bool>("DisableLed")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_led");

                    b.Property<double?>("FlatLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("flat_level");

                    b.Property<string>("GuideLine")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("guide_line");

                    b.Property<int>("LogFlushInterval")
                        .HasColumnType("integer")
                        .HasColumnName("log_flush_interval");

                    b.Property<int?>("MeasurementDuration")
                        .HasColumnType("integer")
                        .HasColumnName("measurement_duration");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("TracePostTrigger")
                        .HasColumnType("double precision")
                        .HasColumnName("trace_post_trigger");

                    b.Property<double?>("TracePreTrigger")
                        .HasColumnType("double precision")
                        .HasColumnName("trace_pre_trigger");

                    b.Property<double?>("TraceSaveLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("trace_save_level");

                    b.Property<bool>("VdvEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vdv_enabled");

                    b.Property<int?>("VdvPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("vdv_period");

                    b.Property<string>("VdvX")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vdv_x");

                    b.Property<string>("VdvY")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vdv_y");

                    b.Property<string>("VdvZ")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vdv_z");

                    b.Property<bool>("VectorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vector_enabled");

                    b.Property<bool>("VtopEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vtop_enabled");

                    b.HasKey("Id")
                        .HasName("pk_omnidots_monitor_status");

                    b.ToTable("omnidots_monitor_status", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel", b =>
                {
                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xfdom")
                        .HasColumnType("double precision")
                        .HasColumnName("x_fdom");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("XvtopOverflow")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop_overflow");

                    b.Property<double?>("Yfdom")
                        .HasColumnType("double precision")
                        .HasColumnName("y_fdom");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("YvtopOverflow")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop_overflow");

                    b.Property<double?>("Zfdom")
                        .HasColumnType("double precision")
                        .HasColumnName("z_fdom");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.Property<double?>("ZvtopOverflow")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop_overflow");

                    b.ToTable("omnidots_peak_level", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel15min", b =>
                {
                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.ToTable((string)null);

                    b.ToView("omnidots_peak_level_15_min", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel1dayPeak", b =>
                {
                    b.Property<DateTime?>("SampleTime")
                        .HasColumnType("date")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.ToTable((string)null);

                    b.ToView("omnidots_peak_level_1_day_peak", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel1min", b =>
                {
                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.ToTable((string)null);

                    b.ToView("omnidots_peak_level_1_min", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel20min", b =>
                {
                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.ToTable((string)null);

                    b.ToView("omnidots_peak_level_20_min", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsPeakLevel5min", b =>
                {
                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sample_time");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<double?>("Xvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("x_vtop");

                    b.Property<double?>("Yvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("y_vtop");

                    b.Property<double?>("Zvtop")
                        .HasColumnType("double precision")
                        .HasColumnName("z_vtop");

                    b.ToTable((string)null);

                    b.ToView("omnidots_peak_level_5_min", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BatteryCharge")
                        .HasColumnType("integer")
                        .HasColumnName("battery_charge");

                    b.Property<string>("ConnectedUsing")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("connected_using");

                    b.Property<DateTime>("Lastseen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastseen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("name");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean")
                        .HasColumnName("online");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.HasKey("Id")
                        .HasName("pk_omnidots_sensor");

                    b.ToTable("omnidots_sensor", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsTrace", b =>
                {
                    b.Property<Guid?>("TraceId")
                        .HasColumnType("uuid")
                        .HasColumnName("omnidots_trace_index_id");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<double?>("Z")
                        .HasColumnType("double precision")
                        .HasColumnName("z");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_omnidots_trace_omnidots_trace_index_id");

                    b.ToTable("omnidots_trace", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsTracesIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("SerialId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_omnidots_trace_index");

                    b.ToTable("omnidots_trace_index", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<DateTime?>("LastGenerated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_generated");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_report_rule");

                    b.ToTable("report_rule", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportRuleSearch", b =>
                {
                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastGenerated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_generated");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.ToTable((string)null);

                    b.ToView("report_rule_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportRuleUserSearch", b =>
                {
                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastGenerated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_generated");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("report_rule_user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportSearch", b =>
                {
                    b.Property<string>("Contracts")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contracts");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_date");

                    b.Property<DateTime>("ReportFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_from");

                    b.Property<string>("ReportLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("report_link");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_name");

                    b.Property<Guid>("ReportRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_rule_id");

                    b.Property<DateTime>("ReportTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_to");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.ToTable((string)null);

                    b.ToView("report_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ReportRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_rule_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_report_user");

                    b.ToTable("report_user", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.ReportUserSearch", b =>
                {
                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_date");

                    b.Property<DateTime>("ReportFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_from");

                    b.Property<string>("ReportLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("report_link");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("report_name");

                    b.Property<Guid>("ReportRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_rule_id");

                    b.Property<DateTime>("ReportTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_to");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("report_user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.SiteSearch", b =>
                {
                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_2");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("Contracts")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contracts");

                    b.Property<string>("County")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postcode");

                    b.Property<string>("SiteAddress")
                        .HasMaxLength(274)
                        .HasColumnType("character varying(274)")
                        .HasColumnName("site_address");

                    b.Property<string>("SiteContact")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("site_contact");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.ToTable((string)null);

                    b.ToView("site_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.SiteUserSearch", b =>
                {
                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_line_2");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("Contracts")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("contracts");

                    b.Property<string>("County")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postcode");

                    b.Property<string>("SiteAddress")
                        .HasMaxLength(274)
                        .HasColumnType("character varying(274)")
                        .HasColumnName("site_address");

                    b.Property<string>("SiteContact")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("site_contact");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("site_user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.SvantekMonitorStatus", b =>
                {
                    b.Property<string>("Active")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("active");

                    b.Property<int?>("Batterycharge")
                        .HasColumnType("integer")
                        .HasColumnName("batterycharge");

                    b.Property<int?>("Batterytimetoempty")
                        .HasColumnType("integer")
                        .HasColumnName("batterytimetoempty");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<int?>("Gsmsignalquality")
                        .HasColumnType("integer")
                        .HasColumnName("gsmsignalquality");

                    b.Property<string>("Isbatterycharging")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("isbatterycharging");

                    b.Property<string>("Isonline")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("isonline");

                    b.Property<string>("Lastlogin")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("lastlogin");

                    b.Property<string>("Lastlogout")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("lastlogout");

                    b.Property<string>("Laststatustimestamp")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("laststatustimestamp");

                    b.Property<string>("Measurementstate")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("measurementstate");

                    b.Property<decimal?>("Meterfirmware")
                        .HasColumnType("numeric(4, 2)")
                        .HasColumnName("meterfirmware");

                    b.Property<int>("PointId")
                        .HasColumnType("integer")
                        .HasColumnName("point_id");

                    b.Property<string>("Powersource")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("powersource");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_id");

                    b.Property<string>("Type")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("type");

                    b.ToTable("svantek_monitor_status", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.UserSearch", b =>
                {
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyRole")
                        .HasColumnType("text")
                        .HasColumnName("company_role");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<int>("NrSites")
                        .HasColumnType("integer")
                        .HasColumnName("nr_sites");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("role");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.ToTable((string)null);

                    b.ToView("user_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.UsersForReportSearch", b =>
                {
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyRole")
                        .HasColumnType("text")
                        .HasColumnName("company_role");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<Guid?>("ReportRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_rule_id");

                    b.Property<string>("Role")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("role");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.ToTable((string)null);

                    b.ToView("users_for_report_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.UsersForSiteSearch", b =>
                {
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyRole")
                        .HasColumnType("text")
                        .HasColumnName("company_role");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<int>("NrSites")
                        .HasColumnType("integer")
                        .HasColumnName("nr_sites");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("role");

                    b.Property<bool?>("SiteContact")
                        .HasColumnType("boolean")
                        .HasColumnName("site_contact");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.ToTable((string)null);

                    b.ToView("users_for_site_search", (string)null);
                });

            modelBuilder.Entity("RVT.DataAccess.EntityModels.Models.OmnidotsTrace", b =>
                {
                    b.HasOne("RVT.DataAccess.EntityModels.Models.OmnidotsTracesIndex", "Trace")
                        .WithMany()
                        .HasForeignKey("TraceId")
                        .HasConstraintName("fk_omnidots_trace_omnidots_trace_index_id");

                    b.Navigation("Trace");
                });
#pragma warning restore 612, 618
        }
    }
}
