<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/._*</DefaultItemExcludes>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <WarningsAsErrors>$(WarningsAsErrors);NU1903;NU1904</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('Tests'))">
    <WarningsAsErrors>$(WarningsAsErrors);MSTEST0001;MSTEST0017;MSTEST0030;MSTEST0032;MSTEST0037;MSTEST0044;MSTEST0052</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/._*.cs" />
    <None Remove="**/._*" />
    <Content Remove="**/._*" />
    <EmbeddedResource Remove="**/._*" />
  </ItemGroup>
</Project>
