<Project>
  <Import Project="../../Directory.Build.props" />

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/._*</DefaultItemExcludes>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('Tests'))">
    <NoWarn>$(NoWarn);MSTEST0001;MSTEST0017;MSTEST0030;MSTEST0032;MSTEST0037;MSTEST0044;MSTEST0052</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/._*.cs" />
    <None Remove="**/._*" />
    <Content Remove="**/._*" />
    <EmbeddedResource Remove="**/._*" />
  </ItemGroup>
</Project>
