<Project>
  <ItemGroup Condition="'$(IsTestProject)' == 'true' And Exists('$(MSBuildThisFileDirectory)testing/Rvt.Monitor.IntegrationTesting/appsettings.Development.json')">
    <None Include="$(MSBuildThisFileDirectory)testing/Rvt.Monitor.IntegrationTesting/appsettings.Development.json">
      <Link>rvt-integration.appsettings.Development.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
