-- Rollback draft for PostgreSQL/TimescaleDB canonical database names.
-- Generated from docs/database/database-name-registry.csv.
-- ASP.NET Identity tables are intentionally excluded from this refactor.
BEGIN;
SET LOCAL lock_timeout = '5s';

-- Column renames.
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "user_name" TO "UserName";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "two_factor_enabled" TO "TwoFactorEnabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "site_contact" TO "SiteContact";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "role" TO "Role";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "phone_number_confirmed" TO "PhoneNumberConfirmed";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "phone_number" TO "PhoneNumber";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "row_count_sites" TO "NrSites";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "normalized_user_name" TO "NormalizedUserName";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "name" TO "Name";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "lockout_end" TO "LockoutEnd";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "lockout_enabled" TO "LockoutEnabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "is_disabled" TO "IsDisabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "email_confirmed" TO "EmailConfirmed";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "email" TO "Email";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "concurrency_stamp" TO "ConcurrencyStamp";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "company_role" TO "CompanyRole";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "access_failed_count" TO "AccessFailedCount";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "user_name" TO "UserName";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "two_factor_enabled" TO "TwoFactorEnabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "role" TO "Role";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "report_rule_id" TO "ReportRuleId";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "phone_number_confirmed" TO "PhoneNumberConfirmed";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "phone_number" TO "PhoneNumber";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "normalized_user_name" TO "NormalizedUserName";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "name" TO "Name";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "lockout_end" TO "LockoutEnd";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "lockout_enabled" TO "LockoutEnabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "is_disabled" TO "IsDisabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "email_confirmed" TO "EmailConfirmed";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "email" TO "Email";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "concurrency_stamp" TO "ConcurrencyStamp";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "company_role" TO "CompanyRole";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "access_failed_count" TO "AccessFailedCount";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "user_name" TO "UserName";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "two_factor_enabled" TO "TwoFactorEnabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "role" TO "Role";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "phone_number_confirmed" TO "PhoneNumberConfirmed";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "phone_number" TO "PhoneNumber";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "row_count_sites" TO "NrSites";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "normalized_user_name" TO "NormalizedUserName";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "name" TO "Name";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "lockout_end" TO "LockoutEnd";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "lockout_enabled" TO "LockoutEnabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "is_disabled" TO "IsDisabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "email_confirmed" TO "EmailConfirmed";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "email" TO "Email";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "concurrency_stamp" TO "ConcurrencyStamp";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "company_role" TO "CompanyRole";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "access_failed_count" TO "AccessFailedCount";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "user_name" TO "UserName";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "recorded_at" TO "Timestamp";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "parameters" TO "Parameters";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "id" TO "ID";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "form_data" TO "FormData";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "controller_action" TO "ControllerAction";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "controller" TO "Controller";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "completed" TO "Completed";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "number_of_samples" TO "NumberOfSamples";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."svantek_monitor_status" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."svantek_monitor_status" RENAME COLUMN "error_count" TO "ErrorCount";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "sun_start_time" TO "SunStartTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "sun_end_time" TO "SunEndTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "start_time" TO "StartTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "sat_start_time" TO "SatStartTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "sat_end_time" TO "SatEndTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "postcode" TO "Postcode";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "end_time" TO "EndTime";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "create_date" TO "CreateDate";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "county" TO "County";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "city" TO "City";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "archived" TO "Archived";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "address_line_2" TO "AddressLine2";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "address_line_1" TO "AddressLine1";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "start_date" TO "StartDate";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "site_contact" TO "SiteContact";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "end_date" TO "EndDate";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "site_address" TO "siteAddress";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "site_contact" TO "SiteContact";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "postcode" TO "Postcode";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "create_date" TO "CreateDate";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "county" TO "County";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "city" TO "City";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "archived" TO "Archived";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "address_line_2" TO "AddressLine2";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "address_line_1" TO "AddressLine1";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "site_address" TO "siteAddress";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "site_contact" TO "SiteContact";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "postcode" TO "Postcode";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "create_date" TO "CreateDate";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "county" TO "County";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "city" TO "City";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "archived" TO "Archived";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "address_line_2" TO "AddressLine2";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "address_line_1" TO "AddressLine1";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "start_time" TO "StartTime";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "is_closed" TO "IsClosed";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "end_time" TO "EndTime";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "day_of_week" TO "DayOfWeek";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "level" TO "Level";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "field" TO "Field";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "collection_time" TO "CollectionTime";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "picture_link" TO "PictureLink";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "created_by" TO "CreatedBy";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "create_date" TO "CreateDate";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "weekdays" TO "Weekdays";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "sundays" TO "Sundays";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "start_time" TO "StartTime";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "saturdays" TO "Saturdays";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "limit_on" TO "LimitOn";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "limit_off" TO "LimitOff";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "is_deleted" TO "IsDeleted";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "is_active" TO "IsActive";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "end_time" TO "EndTime";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "created" TO "Created";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "averaging_period" TO "AveragingPeriod";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "alert_type" TO "AlertType";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "alert_field" TO "AlertField";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "accessed" TO "Accessed";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "send_time" TO "SendTime";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "report_id" TO "ReportId";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "error_message" TO "ErrorMessage";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "address" TO "Address";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "tag" TO "Tag";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "error_time" TO "ErrorTime";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "error" TO "Error";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "report_to" TO "ReportTo";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "report_rule_id" TO "ReportRuleId";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "report_link" TO "ReportLink";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "report_from" TO "ReportFrom";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "report_date" TO "ReportDate";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "report_rule_id" TO "ReportRuleId";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_to" TO "ReportTo";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_rule_id" TO "ReportRuleId";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_name" TO "ReportName";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_link" TO "ReportLink";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_from" TO "ReportFrom";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "report_date" TO "ReportDate";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "deleted" TO "Deleted";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_to" TO "ReportTo";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_rule_id" TO "ReportRuleId";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_name" TO "ReportName";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_link" TO "ReportLink";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_from" TO "ReportFrom";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "report_date" TO "ReportDate";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "deleted" TO "Deleted";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "report_name" TO "ReportName";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "last_generated" TO "LastGenerated";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "deleted" TO "Deleted";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "day_of_week" TO "DayOfWeek";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "day_of_month" TO "DayOfMonth";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "report_name" TO "ReportName";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "last_generated" TO "LastGenerated";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "day_of_week" TO "DayOfWeek";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "day_of_month" TO "DayOfMonth";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "report_name" TO "ReportName";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "last_generated" TO "LastGenerated";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "frequency" TO "Frequency";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "day_of_week" TO "DayOfWeek";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "day_of_month" TO "DayOfMonth";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "z" TO "Z";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "y" TO "Y";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "x" TO "X";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "z" TO "Z";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "y" TO "Y";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "x" TO "X";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "vdv_z" TO "VdvZ";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "vdv_y" TO "VdvY";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "vdv_x" TO "VdvX";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "start_time" TO "StartTime";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "end_time" TO "EndTime";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "z" TO "Z";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "y" TO "Y";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "x" TO "X";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "omnidots_trace_index_id" TO "TraceId";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "online" TO "Online";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "name" TO "Name";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "lastseen" TO "Lastseen";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "connected_using" TO "ConnectedUsing";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "battery_charge" TO "BatteryCharge";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "z_vtop_overflow" TO "ZVtopOverflow";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "z_fdom" TO "ZFdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "y_vtop_overflow" TO "YVtopOverflow";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "y_fdom" TO "YFdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "x_vtop_overflow" TO "XVtopOverflow";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "x_fdom" TO "XFdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "z_vtop" TO "ZVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "y_vtop" TO "YVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "x_vtop" TO "XVtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vtop_enabled" TO "VtopEnabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vector_enabled" TO "VectorEnabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vdv_z" TO "VdvZ";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vdv_y" TO "VdvY";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vdv_x" TO "VdvX";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vdv_period" TO "VdvPeriod";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "vdv_enabled" TO "VdvEnabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "trace_save_level" TO "TraceSaveLevel";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "trace_pre_trigger" TO "TracePreTrigger";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "trace_post_trigger" TO "TracePostTrigger";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "measurement_duration" TO "MeasurementDuration";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "log_flush_interval" TO "LogFlushInterval";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "guide_line" TO "GuideLine";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "flat_level" TO "FlatLevel";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "disable_led" TO "DisableLed";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "data_save_level" TO "DataSaveLevel";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "building_level" TO "BuildingLevel";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "atop_enabled" TO "AtopEnabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "alarm_value" TO "AlarmValue";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "tag" TO "Tag";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "error_time" TO "ErrorTime";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "error" TO "Error";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "send_time" TO "SendTime";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "notification_id" TO "NotificationId";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "error_message" TO "ErrorMessage";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "address" TO "Address";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "recording_link" TO "RecordingLink";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "notification_time" TO "NotificationTime";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "limit_on" TO "LimitOn";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "level" TO "Level";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "closed_time" TO "ClosedTime";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "closed_note" TO "ClosedNote";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "closed_by_user" TO "ClosedByUser";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "averaging_period" TO "AveragingPeriod";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "alert_type" TO "AlertType";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "alert_field" TO "AlertField";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "notification_time" TO "NotificationTime";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "limit_on" TO "LimitOn";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "level" TO "Level";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "last_data_time" TO "LastDataTime";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "contract_id" TO "ContractId";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "closed_date" TO "ClosedDate";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "alert_type" TO "AlertType";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "alert_field" TO "AlertField";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "start_time" TO "StartTime";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "site_user_id" TO "SiteUserId";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "site_id" TO "SiteId";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "sms" TO "SMS";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "end_time" TO "EndTime";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "email" TO "Email";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "notification_time" TO "NotificationTime";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "limit_on" TO "LimitOn";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "level" TO "Level";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "last_data_time" TO "LastDataTime";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "contract_id" TO "ContractId";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "closed_date" TO "ClosedDate";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "alert_type" TO "AlertType";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "alert_field" TO "AlertField";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "tag" TO "Tag";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "error_time" TO "ErrorTime";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "error" TO "Error";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "weather_t" TO "Weather_t";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "weather_rh" TO "Weather_rh";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "weather_p" TO "Weather_p";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "pm_total" TO "PmTotal";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "pm_2_5" TO "Pm2_5";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "pm_10" TO "Pm10";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "pm_1" TO "Pm1";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "avrg" TO "Avrg";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "pm_total" TO "PmTotal";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "pm_2_5" TO "Pm2_5";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "pm_10" TO "Pm10";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "pm_1" TO "Pm1";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_volume_flow_time" TO "OperatingVolumeFlowTimestamp";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_volume_flow_signal_length" TO "OperatingVolumeFlowSignalLength";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_volume_flow" TO "OperatingVolumeFlow";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_velocity" TO "OperatingVelocity";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_tmio" TO "OperatingTMio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_t_led" TO "OperatingTLed";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_t_heating" TO "OperatingTHeating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_span_point_deviation" TO "OperatingSpanPointDeviation";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_sla_offset_adjustment_voltage" TO "OperatingSlaOffsetAdjustmentVoltage";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_sla_noise_level" TO "OperatingSlaNoiseLevel";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_rh_mio" TO "OperatingRHMio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_volume_flow_blower" TO "OperatingPowerVolumeFlowBlower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_separator_blower" TO "OperatingPowerSeparatorBlower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_pmt" TO "OperatingPowerPmt";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_led" TO "OperatingPowerLed";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_housing_blower" TO "OperatingPowerHousingBlower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_power_heating" TO "OperatingPowerHeating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_peak_position_15_s" TO "OperatingPeakPosition15s";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_pmio" TO "OperatingPMio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_flow_correction_factor" TO "OperatingFlowCorrectionFactor";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "operating_auto_calibration_peak_position" TO "OperatingAutoCalibrationPeakPosition";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_weather_station" TO "DigitalWeatherStation";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_volume_flow" TO "DigitalVolumeFlow";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_suction" TO "DigitalSuction";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_sensor_noise" TO "DigitalSensorNoise";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_sensor_led" TO "DigitalSensorLed";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_sensor_data" TO "DigitalSensorData";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_optics_temperature" TO "DigitalOpticsTemperature";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_operating_modus" TO "DigitalOperatingModus";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_liquid_pumps" TO "DigitalLiquidPumps";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_iads_connected" TO "DigitalIadsConnected";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_iads_activated" TO "DigitalIadsActivated";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_iads" TO "DigitalIads";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_global_warning" TO "DigitalGlobalWarning";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_global_error" TO "DigitalGlobalError";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_evaporation_heating" TO "DigitalEvaporationHeating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_droplet_size" TO "DigitalDropletSize";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_count_modus" TO "DigitalCountModus";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_condensation_cooling" TO "DigitalCondensationCooling";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_coincidence" TO "DigitalCoincidence";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_calibration_enable_status" TO "DigitalCalibrationEnableStatus";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_calibration" TO "DigitalCalibration";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "digital_ambient_protection_attached" TO "DigitalAmbientProtectionAttached";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "time_zone" TO "TimeZone";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "offline" TO "Offline";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "model" TO "Model";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "manufacturer" TO "Manufacturer";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "longitude" TO "Longitude";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "location_id" TO "LocationId";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "location_address" TO "LocationAddress";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "listed_at_time" TO "ListedAtTime";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "latitude" TO "Latitude";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "last_data_time_24_hour" TO "LastDataTime24Hour";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "last_data_time_1_min" TO "LastDataTime1Min";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "last_data_time_1_hour" TO "LastDataTime1Hour";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "last_data_time_15_min" TO "LastDataTime15Min";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "firmware_version" TO "FirmwareVersion";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "customer_id" TO "CustomerId";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "customer_display_name" TO "CustomerDisplayName";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "calibration_due" TO "CalibrationDue";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "calibration_date" TO "CalibrationDate";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "battery_status" TO "BatteryStatus";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "what_3_words" TO "What3words";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "off_line" TO "OffLine";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "longitude" TO "Longitude";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "location_id" TO "LocationId";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "latitude" TO "Latitude";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "last_data_time" TO "LastDataTime";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "deployment_id" TO "DeploymentId";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "cautions" TO "Cautions";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "battery" TO "Battery";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "alerts" TO "Alerts";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "active" TO "Active";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "what_3_words" TO "What3words";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "off_line" TO "OffLine";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "monitor_name" TO "MonitorName";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "longitude" TO "Longitude";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "location_id" TO "LocationId";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "latitude" TO "Latitude";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "last_data_time" TO "LastDataTime";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "end_date" TO "EndDate";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "deployment_id" TO "DeploymentId";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "contract_id" TO "ContractId";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "cautions" TO "Cautions";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "battery" TO "Battery";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "alerts" TO "Alerts";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "active" TO "Active";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "what_3_words" TO "What3words";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "type_of_monitor" TO "TypeOfMonitor";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "off_line" TO "OffLine";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "longitude" TO "Longitude";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "location_id" TO "LocationId";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "latitude" TO "Latitude";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "last_data_time" TO "LastDataTime";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "fleet_row_count" TO "FleetNr";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "deployment_id" TO "DeploymentId";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "contract_id" TO "ContractId";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "cautions" TO "Cautions";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "battery" TO "Battery";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "alerts" TO "Alerts";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "title" TO "Title";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "sort_order" TO "SortOrder";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "slug" TO "Slug";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "is_published" TO "IsPublished";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "url" TO "Url";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "title" TO "Title";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "sort_order" TO "SortOrder";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "internal_path" TO "InternalPath";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "help_article_id" TO "HelpArticleId";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "asset_type" TO "AssetType";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "updated_at_utc" TO "UpdatedAtUtc";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "title" TO "Title";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "summary" TO "Summary";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "sort_order" TO "SortOrder";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "slug" TO "Slug";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "help_section_id" TO "SectionId";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "is_published" TO "IsPublished";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "created_at_utc" TO "CreatedAtUtc";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "content_type" TO "ContentType";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "body" TO "Body";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "variables" TO "Variables";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "logged_at" TO "Timestamtp";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "stack_trace" TO "StackTrace";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "source" TO "Source";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "message" TO "Message";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "level" TO "Level";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "host" TO "Host";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "what_3_words" TO "What3words";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "start_date" TO "StartDate";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "picture_link" TO "PictureLink";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "monitor_id" TO "MonitorId";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "location" TO "Location";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "lng" TO "Lng";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "lat" TO "Lat";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "end_date" TO "EndDate";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "contract_id" TO "ContractId";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "row_count" TO "nr";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "alert_type" TO "AlertType";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "alert_state" TO "AlertState";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "row_count" TO "nr";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "user_id" TO "UserId";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "monitor_state" TO "MonitorState";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "on_hire_date" TO "OnHireDate";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "off_hire_date" TO "OffHireDate";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "site_address" TO "siteAddress";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "site_id" TO "SiteiD";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "site_name" TO "SiteName";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "on_hire_date" TO "OnHireDate";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "off_hire_date" TO "OffHireDate";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "contract_number" TO "ContractNumber";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "company_id" TO "CompanyId";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "user_count" TO "nrUsers";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."company" RENAME COLUMN "id" TO "Id";
ALTER TABLE IF EXISTS "public"."company" RENAME COLUMN "company_name" TO "CompanyName";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "serial_id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "sample_time" TO "SampleTime";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "number_of_samples" TO "NumberOfSamples";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "lcmax" TO "LCmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "lceq" TO "LCeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "lc_90" TO "LC90";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "lc_10" TO "LC10";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "lamax" TO "LAmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "laeq" TO "LAeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "la_90" TO "LA90";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "la_10" TO "LA10";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "update_time" TO "UpdateTime";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "status" TO "Status";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "id" TO "SerialId";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "pump_hours" TO "PumpHours";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "filter_change_date" TO "FilterChangeDate";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "error_count" TO "ErrorCount";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "calibration_date" TO "CalibrationDate";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "battery_voltage" TO "BatteryVoltage";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "tag" TO "Tag";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "error_time" TO "ErrorTime";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "error" TO "Error";
ALTER TABLE IF EXISTS "public"."admin_dashboard_data" RENAME COLUMN "row_count" TO "nr";
ALTER TABLE IF EXISTS "public"."admin_dashboard_data" RENAME COLUMN "monitor_state" TO "MonitorState";

-- Relation renames.
ALTER VIEW IF EXISTS "public"."users_for_site_search" RENAME TO "UsersForSiteSearch";
ALTER VIEW IF EXISTS "public"."users_for_report_search" RENAME TO "UsersForReportSearch";
ALTER VIEW IF EXISTS "public"."user_search" RENAME TO "UserSearch";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME TO "UserActionsHistory";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME TO "SvantekNoiseLevels";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME TO "SvantekNoise8HourAverage";
ALTER TABLE IF EXISTS "public"."svantek_monitor_status" RENAME TO "SvantekMonitorStatus";
ALTER TABLE IF EXISTS "public"."site" RENAME TO "Sites";
ALTER TABLE IF EXISTS "public"."site_user" RENAME TO "SiteUsers";
ALTER VIEW IF EXISTS "public"."site_user_search" RENAME TO "SiteUserSearch";
ALTER VIEW IF EXISTS "public"."site_search" RENAME TO "SiteSearch";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME TO "SiteOperatingHours";
ALTER TABLE IF EXISTS "public"."site_average" RENAME TO "SiteAverages";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME TO "SiteArchived";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME TO "RvtAlertRules";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME TO "ReportsSent";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME TO "ReportsErrorMessages";
ALTER TABLE IF EXISTS "public"."report" RENAME TO "Reports";
ALTER TABLE IF EXISTS "public"."report_user" RENAME TO "ReportUsers";
ALTER VIEW IF EXISTS "public"."report_user_search" RENAME TO "ReportUserSearch";
ALTER VIEW IF EXISTS "public"."report_search" RENAME TO "ReportSearch";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME TO "ReportRules";
ALTER VIEW IF EXISTS "public"."report_rule_user_search" RENAME TO "ReportRuleUserSearch";
ALTER VIEW IF EXISTS "public"."report_rule_search" RENAME TO "ReportRuleSearch";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME TO "OmnidotsVeffLevels";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME TO "OmnidotsVdvLevels";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME TO "OmnidotsTracesIndex";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME TO "OmnidotsTraces";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME TO "OmnidotsSensors";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME TO "OmnidotsPeakLevels";
ALTER VIEW IF EXISTS "public"."omnidots_peak_level_5_min" RENAME TO "OmnidotsPeakLevel5min";
ALTER VIEW IF EXISTS "public"."omnidots_peak_level_20_min" RENAME TO "OmnidotsPeakLevel20min";
ALTER VIEW IF EXISTS "public"."omnidots_peak_level_1_min" RENAME TO "OmnidotsPeakLevel1min";
ALTER VIEW IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME TO "OmnidotsPeakLevel1dayPeak";
ALTER VIEW IF EXISTS "public"."omnidots_peak_level_15_min" RENAME TO "OmnidotsPeakLevel15min";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME TO "OmnidotsMonitorStatus";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME TO "OmnidotsErrorMessages";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME TO "NotificationsSent";
ALTER TABLE IF EXISTS "public"."notification" RENAME TO "Notifications";
ALTER VIEW IF EXISTS "public"."notification_user_search" RENAME TO "NotificationUserSearch";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME TO "NotificationSettings";
ALTER VIEW IF EXISTS "public"."notification_search" RENAME TO "NotificationSearch";
ALTER VIEW IF EXISTS "public"."noise_level_site_avg" RENAME TO "NoiseLevelSiteAvg";
ALTER VIEW IF EXISTS "public"."noise_level_1_hour_avg" RENAME TO "NoiseLevel1hourAvg";
ALTER VIEW IF EXISTS "public"."noise_level_1_day_avg" RENAME TO "NoiseLevel1dayAvg";
ALTER VIEW IF EXISTS "public"."noise_level_15_min_avg" RENAME TO "NoiseLevel15minAvg";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME TO "MyAtmErrorMessages";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME TO "MyAtmDustLevels";
ALTER VIEW IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME TO "MyAtmDustLevel8hourAvg";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME TO "MyAtmAccessoryInfo";
ALTER TABLE IF EXISTS "public"."monitor" RENAME TO "MonitorsList";
ALTER VIEW IF EXISTS "public"."monitor_user_search" RENAME TO "MonitorUserSearch";
ALTER VIEW IF EXISTS "public"."monitor_search" RENAME TO "MonitorSearch";
ALTER VIEW IF EXISTS "public"."monitor_current_search" RENAME TO "MonitorCurrentSearch";
ALTER TABLE IF EXISTS "public"."help_section" RENAME TO "HelpSections";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME TO "HelpAssets";
ALTER TABLE IF EXISTS "public"."help_article" RENAME TO "HelpArticles";
ALTER TABLE IF EXISTS "public"."error_log" RENAME TO "ErrorLog";
ALTER TABLE IF EXISTS "public"."deployment" RENAME TO "Deployments";
ALTER VIEW IF EXISTS "public"."customer_dashboard_notification_data" RENAME TO "CustomerDashboardNotificationData";
ALTER VIEW IF EXISTS "public"."customer_dashboard_monitor_data" RENAME TO "CustomerDashboardMonitorData";
ALTER TABLE IF EXISTS "public"."contract" RENAME TO "Contracts";
ALTER VIEW IF EXISTS "public"."contract_search" RENAME TO "ContractSearch";
ALTER VIEW IF EXISTS "public"."company_search" RENAME TO "CompanySearch";
ALTER TABLE IF EXISTS "public"."company" RENAME TO "Companies";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME TO "AirQNoiseLevels";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME TO "AirQNoise8HourAverage";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME TO "AirQMonitorStatus";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME TO "AirQErrorMessages";
ALTER VIEW IF EXISTS "public"."admin_dashboard_data" RENAME TO "AdminDashboardData";

COMMIT;
