-- Canonical database naming migration draft for PostgreSQL/TimescaleDB.
-- Generated from docs/database/database-name-registry.csv.
-- ASP.NET Identity tables are intentionally excluded from this refactor.
-- Review and rehearse on a cloned database before production use.
-- Run database/postgres/canonical_constraint_index_naming.sql after this script.
BEGIN;
SET LOCAL lock_timeout = '5s';

-- Relation renames.
ALTER VIEW IF EXISTS "public"."AdminDashboardData" RENAME TO "admin_dashboard_data";
ALTER TABLE IF EXISTS "public"."AirQErrorMessages" RENAME TO "air_q_error_message";
ALTER TABLE IF EXISTS "public"."AirQMonitorStatus" RENAME TO "air_q_monitor_status";
ALTER TABLE IF EXISTS "public"."AirQNoise8HourAverage" RENAME TO "air_q_noise_8_hour_average";
ALTER TABLE IF EXISTS "public"."AirQNoiseLevels" RENAME TO "air_q_noise_level";
ALTER TABLE IF EXISTS "public"."Companies" RENAME TO "company";
ALTER VIEW IF EXISTS "public"."CompanySearch" RENAME TO "company_search";
ALTER VIEW IF EXISTS "public"."ContractSearch" RENAME TO "contract_search";
ALTER TABLE IF EXISTS "public"."Contracts" RENAME TO "contract";
ALTER VIEW IF EXISTS "public"."CustomerDashboardMonitorData" RENAME TO "customer_dashboard_monitor_data";
ALTER VIEW IF EXISTS "public"."CustomerDashboardNotificationData" RENAME TO "customer_dashboard_notification_data";
ALTER TABLE IF EXISTS "public"."Deployments" RENAME TO "deployment";
ALTER TABLE IF EXISTS "public"."ErrorLog" RENAME TO "error_log";
ALTER TABLE IF EXISTS "public"."HelpArticles" RENAME TO "help_article";
ALTER TABLE IF EXISTS "public"."HelpAssets" RENAME TO "help_asset";
ALTER TABLE IF EXISTS "public"."HelpSections" RENAME TO "help_section";
ALTER VIEW IF EXISTS "public"."MonitorCurrentSearch" RENAME TO "monitor_current_search";
ALTER VIEW IF EXISTS "public"."MonitorSearch" RENAME TO "monitor_search";
ALTER VIEW IF EXISTS "public"."MonitorUserSearch" RENAME TO "monitor_user_search";
ALTER TABLE IF EXISTS "public"."MonitorsList" RENAME TO "monitor";
ALTER TABLE IF EXISTS "public"."MyAtmAccessoryInfo" RENAME TO "my_atm_accessory_info";
ALTER VIEW IF EXISTS "public"."MyAtmDustLevel8hourAvg" RENAME TO "my_atm_dust_level_8_hour_avg";
ALTER TABLE IF EXISTS "public"."MyAtmDustLevels" RENAME TO "my_atm_dust_level";
ALTER TABLE IF EXISTS "public"."MyAtmErrorMessages" RENAME TO "my_atm_error_message";
ALTER VIEW IF EXISTS "public"."NoiseLevel15minAvg" RENAME TO "noise_level_15_min_avg";
ALTER VIEW IF EXISTS "public"."NoiseLevel1dayAvg" RENAME TO "noise_level_1_day_avg";
ALTER VIEW IF EXISTS "public"."NoiseLevel1hourAvg" RENAME TO "noise_level_1_hour_avg";
ALTER VIEW IF EXISTS "public"."NoiseLevelSiteAvg" RENAME TO "noise_level_site_avg";
ALTER VIEW IF EXISTS "public"."NotificationSearch" RENAME TO "notification_search";
ALTER TABLE IF EXISTS "public"."NotificationSettings" RENAME TO "notification_setting";
ALTER VIEW IF EXISTS "public"."NotificationUserSearch" RENAME TO "notification_user_search";
ALTER TABLE IF EXISTS "public"."Notifications" RENAME TO "notification";
ALTER TABLE IF EXISTS "public"."NotificationsSent" RENAME TO "notification_sent";
ALTER TABLE IF EXISTS "public"."OmnidotsErrorMessages" RENAME TO "omnidots_error_message";
ALTER TABLE IF EXISTS "public"."OmnidotsMonitorStatus" RENAME TO "omnidots_monitor_status";
ALTER VIEW IF EXISTS "public"."OmnidotsPeakLevel15min" RENAME TO "omnidots_peak_level_15_min";
ALTER VIEW IF EXISTS "public"."OmnidotsPeakLevel1dayPeak" RENAME TO "omnidots_peak_level_1_day_peak";
ALTER VIEW IF EXISTS "public"."OmnidotsPeakLevel1min" RENAME TO "omnidots_peak_level_1_min";
ALTER VIEW IF EXISTS "public"."OmnidotsPeakLevel20min" RENAME TO "omnidots_peak_level_20_min";
ALTER VIEW IF EXISTS "public"."OmnidotsPeakLevel5min" RENAME TO "omnidots_peak_level_5_min";
ALTER TABLE IF EXISTS "public"."OmnidotsPeakLevels" RENAME TO "omnidots_peak_level";
ALTER TABLE IF EXISTS "public"."OmnidotsSensors" RENAME TO "omnidots_sensor";
ALTER TABLE IF EXISTS "public"."OmnidotsTraces" RENAME TO "omnidots_trace";
ALTER TABLE IF EXISTS "public"."OmnidotsTracesIndex" RENAME TO "omnidots_trace_index";
ALTER TABLE IF EXISTS "public"."OmnidotsVdvLevels" RENAME TO "omnidots_vdv_level";
ALTER TABLE IF EXISTS "public"."OmnidotsVeffLevels" RENAME TO "omnidots_veff_level";
ALTER VIEW IF EXISTS "public"."ReportRuleSearch" RENAME TO "report_rule_search";
ALTER VIEW IF EXISTS "public"."ReportRuleUserSearch" RENAME TO "report_rule_user_search";
ALTER TABLE IF EXISTS "public"."ReportRules" RENAME TO "report_rule";
ALTER VIEW IF EXISTS "public"."ReportSearch" RENAME TO "report_search";
ALTER VIEW IF EXISTS "public"."ReportUserSearch" RENAME TO "report_user_search";
ALTER TABLE IF EXISTS "public"."ReportUsers" RENAME TO "report_user";
ALTER TABLE IF EXISTS "public"."Reports" RENAME TO "report";
ALTER TABLE IF EXISTS "public"."ReportsErrorMessages" RENAME TO "report_error_message";
ALTER TABLE IF EXISTS "public"."ReportsSent" RENAME TO "report_sent";
ALTER TABLE IF EXISTS "public"."RvtAlertRules" RENAME TO "rvt_alert_rule";
ALTER TABLE IF EXISTS "public"."SiteArchived" RENAME TO "site_archived";
ALTER TABLE IF EXISTS "public"."SiteAverages" RENAME TO "site_average";
ALTER TABLE IF EXISTS "public"."SiteOperatingHours" RENAME TO "site_operating_hour";
ALTER VIEW IF EXISTS "public"."SiteSearch" RENAME TO "site_search";
ALTER VIEW IF EXISTS "public"."SiteUserSearch" RENAME TO "site_user_search";
ALTER TABLE IF EXISTS "public"."SiteUsers" RENAME TO "site_user";
ALTER TABLE IF EXISTS "public"."Sites" RENAME TO "site";
ALTER TABLE IF EXISTS "public"."SvantekMonitorStatus" RENAME TO "svantek_monitor_status";
ALTER TABLE IF EXISTS "public"."SvantekNoise8HourAverage" RENAME TO "svantek_noise_8_hour_average";
ALTER TABLE IF EXISTS "public"."SvantekNoiseLevels" RENAME TO "svantek_noise_level";
ALTER TABLE IF EXISTS "public"."UserActionsHistory" RENAME TO "user_action_history";
ALTER VIEW IF EXISTS "public"."UserSearch" RENAME TO "user_search";
ALTER VIEW IF EXISTS "public"."UsersForReportSearch" RENAME TO "users_for_report_search";
ALTER VIEW IF EXISTS "public"."UsersForSiteSearch" RENAME TO "users_for_site_search";

-- Column renames.
ALTER TABLE IF EXISTS "public"."admin_dashboard_data" RENAME COLUMN "MonitorState" TO "monitor_state";
ALTER TABLE IF EXISTS "public"."admin_dashboard_data" RENAME COLUMN "nr" TO "row_count";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "Error" TO "error";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "ErrorTime" TO "error_time";
ALTER TABLE IF EXISTS "public"."air_q_error_message" RENAME COLUMN "Tag" TO "tag";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "BatteryVoltage" TO "battery_voltage";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "CalibrationDate" TO "calibration_date";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "ErrorCount" TO "error_count";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "FilterChangeDate" TO "filter_change_date";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "PumpHours" TO "pump_hours";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "SerialId" TO "id";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "Status" TO "status";
ALTER TABLE IF EXISTS "public"."air_q_monitor_status" RENAME COLUMN "UpdateTime" TO "update_time";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "NumberOfSamples" TO "number_of_samples";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."air_q_noise_8_hour_average" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."air_q_noise_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."company" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."company" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."company_search" RENAME COLUMN "nrUsers" TO "user_count";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "OffHireDate" TO "off_hire_date";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "OnHireDate" TO "on_hire_date";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."contract_search" RENAME COLUMN "siteAddress" TO "site_address";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "OffHireDate" TO "off_hire_date";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "OnHireDate" TO "on_hire_date";
ALTER TABLE IF EXISTS "public"."contract" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "MonitorState" TO "monitor_state";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."customer_dashboard_monitor_data" RENAME COLUMN "nr" TO "row_count";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "AlertState" TO "alert_state";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "AlertType" TO "alert_type";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."customer_dashboard_notification_data" RENAME COLUMN "nr" TO "row_count";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "ContractId" TO "contract_id";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "EndDate" TO "end_date";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "Lat" TO "lat";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "Lng" TO "lng";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "Location" TO "location";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "PictureLink" TO "picture_link";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "StartDate" TO "start_date";
ALTER TABLE IF EXISTS "public"."deployment" RENAME COLUMN "What3words" TO "what_3_words";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Host" TO "host";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Level" TO "level";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Message" TO "message";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Source" TO "source";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "StackTrace" TO "stack_trace";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Timestamtp" TO "logged_at";
ALTER TABLE IF EXISTS "public"."error_log" RENAME COLUMN "Variables" TO "variables";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "Body" TO "body";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "ContentType" TO "content_type";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "CreatedAtUtc" TO "created_at_utc";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "IsPublished" TO "is_published";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "SectionId" TO "help_section_id";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "Slug" TO "slug";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "SortOrder" TO "sort_order";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "Summary" TO "summary";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "Title" TO "title";
ALTER TABLE IF EXISTS "public"."help_article" RENAME COLUMN "UpdatedAtUtc" TO "updated_at_utc";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "AssetType" TO "asset_type";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "HelpArticleId" TO "help_article_id";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "InternalPath" TO "internal_path";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "SortOrder" TO "sort_order";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "Title" TO "title";
ALTER TABLE IF EXISTS "public"."help_asset" RENAME COLUMN "Url" TO "url";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "IsPublished" TO "is_published";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "Slug" TO "slug";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "SortOrder" TO "sort_order";
ALTER TABLE IF EXISTS "public"."help_section" RENAME COLUMN "Title" TO "title";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Alerts" TO "alerts";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Battery" TO "battery";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Cautions" TO "cautions";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "ContractId" TO "contract_id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "DeploymentId" TO "deployment_id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "LastDataTime" TO "last_data_time";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Latitude" TO "latitude";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "LocationId" TO "location_id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "Longitude" TO "longitude";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "OffLine" TO "off_line";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."monitor_current_search" RENAME COLUMN "What3words" TO "what_3_words";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Active" TO "active";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Alerts" TO "alerts";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Battery" TO "battery";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Cautions" TO "cautions";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "ContractId" TO "contract_id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "DeploymentId" TO "deployment_id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "EndDate" TO "end_date";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "LastDataTime" TO "last_data_time";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Latitude" TO "latitude";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "LocationId" TO "location_id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "Longitude" TO "longitude";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "MonitorName" TO "monitor_name";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "OffLine" TO "off_line";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."monitor_search" RENAME COLUMN "What3words" TO "what_3_words";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Active" TO "active";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Alerts" TO "alerts";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Battery" TO "battery";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Cautions" TO "cautions";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "DeploymentId" TO "deployment_id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "LastDataTime" TO "last_data_time";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Latitude" TO "latitude";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "LocationId" TO "location_id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "Longitude" TO "longitude";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "OffLine" TO "off_line";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."monitor_user_search" RENAME COLUMN "What3words" TO "what_3_words";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "BatteryStatus" TO "battery_status";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "CalibrationDate" TO "calibration_date";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "CalibrationDue" TO "calibration_due";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "CustomerDisplayName" TO "customer_display_name";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "CustomerId" TO "customer_id";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "FirmwareVersion" TO "firmware_version";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LastDataTime15Min" TO "last_data_time_15_min";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LastDataTime1Hour" TO "last_data_time_1_hour";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LastDataTime1Min" TO "last_data_time_1_min";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LastDataTime24Hour" TO "last_data_time_24_hour";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Latitude" TO "latitude";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "ListedAtTime" TO "listed_at_time";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LocationAddress" TO "location_address";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "LocationId" TO "location_id";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Longitude" TO "longitude";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Manufacturer" TO "manufacturer";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Model" TO "model";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "Offline" TO "offline";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "TimeZone" TO "time_zone";
ALTER TABLE IF EXISTS "public"."monitor" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalAmbientProtectionAttached" TO "digital_ambient_protection_attached";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalCalibration" TO "digital_calibration";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalCalibrationEnableStatus" TO "digital_calibration_enable_status";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalCoincidence" TO "digital_coincidence";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalCondensationCooling" TO "digital_condensation_cooling";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalCountModus" TO "digital_count_modus";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalDropletSize" TO "digital_droplet_size";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalEvaporationHeating" TO "digital_evaporation_heating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalGlobalError" TO "digital_global_error";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalGlobalWarning" TO "digital_global_warning";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalIads" TO "digital_iads";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalIadsActivated" TO "digital_iads_activated";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalIadsConnected" TO "digital_iads_connected";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalLiquidPumps" TO "digital_liquid_pumps";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalOperatingModus" TO "digital_operating_modus";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalOpticsTemperature" TO "digital_optics_temperature";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalSensorData" TO "digital_sensor_data";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalSensorLed" TO "digital_sensor_led";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalSensorNoise" TO "digital_sensor_noise";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalSuction" TO "digital_suction";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalVolumeFlow" TO "digital_volume_flow";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "DigitalWeatherStation" TO "digital_weather_station";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingAutoCalibrationPeakPosition" TO "operating_auto_calibration_peak_position";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingFlowCorrectionFactor" TO "operating_flow_correction_factor";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPMio" TO "operating_pmio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPeakPosition15s" TO "operating_peak_position_15_s";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerHeating" TO "operating_power_heating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerHousingBlower" TO "operating_power_housing_blower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerLed" TO "operating_power_led";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerPmt" TO "operating_power_pmt";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerSeparatorBlower" TO "operating_power_separator_blower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingPowerVolumeFlowBlower" TO "operating_power_volume_flow_blower";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingRHMio" TO "operating_rh_mio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingSlaNoiseLevel" TO "operating_sla_noise_level";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingSlaOffsetAdjustmentVoltage" TO "operating_sla_offset_adjustment_voltage";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingSpanPointDeviation" TO "operating_span_point_deviation";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingTHeating" TO "operating_t_heating";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingTLed" TO "operating_t_led";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingTMio" TO "operating_tmio";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingVelocity" TO "operating_velocity";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingVolumeFlow" TO "operating_volume_flow";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingVolumeFlowSignalLength" TO "operating_volume_flow_signal_length";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "OperatingVolumeFlowTimestamp" TO "operating_volume_flow_time";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."my_atm_accessory_info" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "Pm1" TO "pm_1";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "Pm10" TO "pm_10";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "Pm2_5" TO "pm_2_5";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "PmTotal" TO "pm_total";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level_8_hour_avg" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Avrg" TO "avrg";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Pm1" TO "pm_1";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Pm10" TO "pm_10";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Pm2_5" TO "pm_2_5";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "PmTotal" TO "pm_total";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Weather_p" TO "weather_p";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Weather_rh" TO "weather_rh";
ALTER TABLE IF EXISTS "public"."my_atm_dust_level" RENAME COLUMN "Weather_t" TO "weather_t";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "Error" TO "error";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "ErrorTime" TO "error_time";
ALTER TABLE IF EXISTS "public"."my_atm_error_message" RENAME COLUMN "Tag" TO "tag";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."noise_level_15_min_avg" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."noise_level_1_day_avg" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."noise_level_1_hour_avg" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."noise_level_site_avg" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "AlertField" TO "alert_field";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "AlertType" TO "alert_type";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "ClosedDate" TO "closed_date";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "ContractId" TO "contract_id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "LastDataTime" TO "last_data_time";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "Level" TO "level";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "LimitOn" TO "limit_on";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "NotificationTime" TO "notification_time";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."notification_search" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "Email" TO "email";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "EndTime" TO "end_time";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "SMS" TO "sms";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "SiteUserId" TO "site_user_id";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "StartTime" TO "start_time";
ALTER TABLE IF EXISTS "public"."notification_setting" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "AlertField" TO "alert_field";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "AlertType" TO "alert_type";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "ClosedDate" TO "closed_date";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "ContractId" TO "contract_id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "ContractNumber" TO "contract_number";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "FleetNr" TO "fleet_row_count";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "LastDataTime" TO "last_data_time";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "Level" TO "level";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "LimitOn" TO "limit_on";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "NotificationTime" TO "notification_time";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "SiteiD" TO "site_id";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "TypeOfMonitor" TO "type_of_monitor";
ALTER TABLE IF EXISTS "public"."notification_user_search" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "AlertField" TO "alert_field";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "AlertType" TO "alert_type";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "AveragingPeriod" TO "averaging_period";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "ClosedByUser" TO "closed_by_user";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "ClosedNote" TO "closed_note";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "ClosedTime" TO "closed_time";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "Level" TO "level";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "LimitOn" TO "limit_on";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "NotificationTime" TO "notification_time";
ALTER TABLE IF EXISTS "public"."notification" RENAME COLUMN "RecordingLink" TO "recording_link";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "Address" TO "address";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "ErrorMessage" TO "error_message";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "NotificationId" TO "notification_id";
ALTER TABLE IF EXISTS "public"."notification_sent" RENAME COLUMN "SendTime" TO "send_time";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "Error" TO "error";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "ErrorTime" TO "error_time";
ALTER TABLE IF EXISTS "public"."omnidots_error_message" RENAME COLUMN "Tag" TO "tag";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "AlarmValue" TO "alarm_value";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "AtopEnabled" TO "atop_enabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "BuildingLevel" TO "building_level";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "DataSaveLevel" TO "data_save_level";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "DisableLed" TO "disable_led";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "FlatLevel" TO "flat_level";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "GuideLine" TO "guide_line";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "LogFlushInterval" TO "log_flush_interval";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "MeasurementDuration" TO "measurement_duration";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "TracePostTrigger" TO "trace_post_trigger";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "TracePreTrigger" TO "trace_pre_trigger";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "TraceSaveLevel" TO "trace_save_level";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VdvEnabled" TO "vdv_enabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VdvPeriod" TO "vdv_period";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VdvX" TO "vdv_x";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VdvY" TO "vdv_y";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VdvZ" TO "vdv_z";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VectorEnabled" TO "vector_enabled";
ALTER TABLE IF EXISTS "public"."omnidots_monitor_status" RENAME COLUMN "VtopEnabled" TO "vtop_enabled";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_15_min" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_day_peak" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_1_min" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_20_min" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level_5_min" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "XFdom" TO "x_fdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "XVtop" TO "x_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "XVtopOverflow" TO "x_vtop_overflow";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "YFdom" TO "y_fdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "YVtop" TO "y_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "YVtopOverflow" TO "y_vtop_overflow";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "ZFdom" TO "z_fdom";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "ZVtop" TO "z_vtop";
ALTER TABLE IF EXISTS "public"."omnidots_peak_level" RENAME COLUMN "ZVtopOverflow" TO "z_vtop_overflow";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "BatteryCharge" TO "battery_charge";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "ConnectedUsing" TO "connected_using";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "Lastseen" TO "lastseen";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "Name" TO "name";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "Online" TO "online";
ALTER TABLE IF EXISTS "public"."omnidots_sensor" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "TraceId" TO "omnidots_trace_index_id";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "X" TO "x";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "Y" TO "y";
ALTER TABLE IF EXISTS "public"."omnidots_trace" RENAME COLUMN "Z" TO "z";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "EndTime" TO "end_time";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_trace_index" RENAME COLUMN "StartTime" TO "start_time";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "VdvX" TO "vdv_x";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "VdvY" TO "vdv_y";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "VdvZ" TO "vdv_z";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "X" TO "x";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "Y" TO "y";
ALTER TABLE IF EXISTS "public"."omnidots_vdv_level" RENAME COLUMN "Z" TO "z";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "X" TO "x";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "Y" TO "y";
ALTER TABLE IF EXISTS "public"."omnidots_veff_level" RENAME COLUMN "Z" TO "z";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "DayOfMonth" TO "day_of_month";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "DayOfWeek" TO "day_of_week";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "LastGenerated" TO "last_generated";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "ReportName" TO "report_name";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_rule_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "DayOfMonth" TO "day_of_month";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "DayOfWeek" TO "day_of_week";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "LastGenerated" TO "last_generated";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "ReportName" TO "report_name";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."report_rule_user_search" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "DayOfMonth" TO "day_of_month";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "DayOfWeek" TO "day_of_week";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "Deleted" TO "deleted";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "LastGenerated" TO "last_generated";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "ReportName" TO "report_name";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_rule" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "Deleted" TO "deleted";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportDate" TO "report_date";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportFrom" TO "report_from";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportLink" TO "report_link";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportName" TO "report_name";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportRuleId" TO "report_rule_id";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "ReportTo" TO "report_to";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "Deleted" TO "deleted";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportDate" TO "report_date";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportFrom" TO "report_from";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportLink" TO "report_link";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportName" TO "report_name";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportRuleId" TO "report_rule_id";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "ReportTo" TO "report_to";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."report_user_search" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "ReportRuleId" TO "report_rule_id";
ALTER TABLE IF EXISTS "public"."report_user" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "Frequency" TO "frequency";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "ReportDate" TO "report_date";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "ReportFrom" TO "report_from";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "ReportLink" TO "report_link";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "ReportRuleId" TO "report_rule_id";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "ReportTo" TO "report_to";
ALTER TABLE IF EXISTS "public"."report" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "Error" TO "error";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "ErrorTime" TO "error_time";
ALTER TABLE IF EXISTS "public"."report_error_message" RENAME COLUMN "Tag" TO "tag";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "Address" TO "address";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "ErrorMessage" TO "error_message";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "ReportId" TO "report_id";
ALTER TABLE IF EXISTS "public"."report_sent" RENAME COLUMN "SendTime" TO "send_time";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Accessed" TO "accessed";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "AlertField" TO "alert_field";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "AlertType" TO "alert_type";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "AveragingPeriod" TO "averaging_period";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Created" TO "created";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "EndTime" TO "end_time";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "IsActive" TO "is_active";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "IsDeleted" TO "is_deleted";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "LimitOff" TO "limit_off";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "LimitOn" TO "limit_on";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Saturdays" TO "saturdays";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "StartTime" TO "start_time";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Sundays" TO "sundays";
ALTER TABLE IF EXISTS "public"."rvt_alert_rule" RENAME COLUMN "Weekdays" TO "weekdays";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "CreateDate" TO "create_date";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "CreatedBy" TO "created_by";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "PictureLink" TO "picture_link";
ALTER TABLE IF EXISTS "public"."site_archived" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "CollectionTime" TO "collection_time";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "Field" TO "field";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "Level" TO "level";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "MonitorId" TO "monitor_id";
ALTER TABLE IF EXISTS "public"."site_average" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "DayOfWeek" TO "day_of_week";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "EndTime" TO "end_time";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "IsClosed" TO "is_closed";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."site_operating_hour" RENAME COLUMN "StartTime" TO "start_time";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "AddressLine1" TO "address_line_1";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "AddressLine2" TO "address_line_2";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "Archived" TO "archived";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "City" TO "city";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "County" TO "county";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "CreateDate" TO "create_date";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "Postcode" TO "postcode";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "SiteContact" TO "site_contact";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."site_search" RENAME COLUMN "siteAddress" TO "site_address";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "AddressLine1" TO "address_line_1";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "AddressLine2" TO "address_line_2";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "Archived" TO "archived";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "City" TO "city";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "County" TO "county";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "CreateDate" TO "create_date";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "Postcode" TO "postcode";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "SiteContact" TO "site_contact";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."site_user_search" RENAME COLUMN "siteAddress" TO "site_address";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "EndDate" TO "end_date";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "SiteContact" TO "site_contact";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "StartDate" TO "start_date";
ALTER TABLE IF EXISTS "public"."site_user" RENAME COLUMN "UserId" TO "user_id";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "AddressLine1" TO "address_line_1";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "AddressLine2" TO "address_line_2";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "Archived" TO "archived";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "City" TO "city";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "County" TO "county";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "CreateDate" TO "create_date";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "EndTime" TO "end_time";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "Postcode" TO "postcode";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "SatEndTime" TO "sat_end_time";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "SatStartTime" TO "sat_start_time";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "SiteName" TO "site_name";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "StartTime" TO "start_time";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "SunEndTime" TO "sun_end_time";
ALTER TABLE IF EXISTS "public"."site" RENAME COLUMN "SunStartTime" TO "sun_start_time";
ALTER TABLE IF EXISTS "public"."svantek_monitor_status" RENAME COLUMN "ErrorCount" TO "error_count";
ALTER TABLE IF EXISTS "public"."svantek_monitor_status" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "NumberOfSamples" TO "number_of_samples";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."svantek_noise_8_hour_average" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LA10" TO "la_10";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LA90" TO "la_90";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LAeq" TO "laeq";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LAmax" TO "lamax";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LC10" TO "lc_10";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LC90" TO "lc_90";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LCeq" TO "lceq";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "LCmax" TO "lcmax";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "SampleTime" TO "sample_time";
ALTER TABLE IF EXISTS "public"."svantek_noise_level" RENAME COLUMN "SerialId" TO "serial_id";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "Completed" TO "completed";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "Controller" TO "controller";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "ControllerAction" TO "controller_action";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "FormData" TO "form_data";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "ID" TO "id";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "Parameters" TO "parameters";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "Timestamp" TO "recorded_at";
ALTER TABLE IF EXISTS "public"."user_action_history" RENAME COLUMN "UserName" TO "user_name";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "AccessFailedCount" TO "access_failed_count";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "CompanyRole" TO "company_role";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "ConcurrencyStamp" TO "concurrency_stamp";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "Email" TO "email";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "EmailConfirmed" TO "email_confirmed";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "IsDisabled" TO "is_disabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "LockoutEnabled" TO "lockout_enabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "LockoutEnd" TO "lockout_end";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "Name" TO "name";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "NormalizedUserName" TO "normalized_user_name";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "NrSites" TO "row_count_sites";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "PhoneNumber" TO "phone_number";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "PhoneNumberConfirmed" TO "phone_number_confirmed";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "Role" TO "role";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "TwoFactorEnabled" TO "two_factor_enabled";
ALTER TABLE IF EXISTS "public"."user_search" RENAME COLUMN "UserName" TO "user_name";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "AccessFailedCount" TO "access_failed_count";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "CompanyRole" TO "company_role";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "ConcurrencyStamp" TO "concurrency_stamp";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "Email" TO "email";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "EmailConfirmed" TO "email_confirmed";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "IsDisabled" TO "is_disabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "LockoutEnabled" TO "lockout_enabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "LockoutEnd" TO "lockout_end";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "Name" TO "name";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "NormalizedUserName" TO "normalized_user_name";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "PhoneNumber" TO "phone_number";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "PhoneNumberConfirmed" TO "phone_number_confirmed";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "ReportRuleId" TO "report_rule_id";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "Role" TO "role";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "TwoFactorEnabled" TO "two_factor_enabled";
ALTER TABLE IF EXISTS "public"."users_for_report_search" RENAME COLUMN "UserName" TO "user_name";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "AccessFailedCount" TO "access_failed_count";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "CompanyId" TO "company_id";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "CompanyName" TO "company_name";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "CompanyRole" TO "company_role";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "ConcurrencyStamp" TO "concurrency_stamp";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "Email" TO "email";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "EmailConfirmed" TO "email_confirmed";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "Id" TO "id";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "IsDisabled" TO "is_disabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "LockoutEnabled" TO "lockout_enabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "LockoutEnd" TO "lockout_end";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "Name" TO "name";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "NormalizedUserName" TO "normalized_user_name";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "NrSites" TO "row_count_sites";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "PhoneNumber" TO "phone_number";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "PhoneNumberConfirmed" TO "phone_number_confirmed";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "Role" TO "role";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "SiteContact" TO "site_contact";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "SiteId" TO "site_id";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "TwoFactorEnabled" TO "two_factor_enabled";
ALTER TABLE IF EXISTS "public"."users_for_site_search" RENAME COLUMN "UserName" TO "user_name";

COMMIT;
